name: DockerBuildAndPush

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --output-path=docs --base-href=/

      - name: Docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Download and run base httpd image
        run: docker run -d --name http_base httpd

      - name: Copy compiled app into httpd container
        run: docker cp docs/. http_base:/usr/local/apache2/htdocs

      - name: Commit customized httpd image
        run: docker commit http_base ${{ secrets.DOCKER_USER }}/mycv:${{ github.sha }}

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USER }}/mycv:${{ github.sha }}
